// generated by Fast Light User Interface Designer (fluid) version 0.99

#include "mglgui.H"

Fl_Menu_Item menu_[] = {
 {"&FILE", 0,  0, 0, 64, 0, 0, 14, 0},
 {"READ", 0,  0, 0, 0, 0, 0, 14, 0},
 {0},
 {"&OPTIONS", 0,  0, 0, 64, 0, 0, 14, 0},
 {"&Colors", 0x80063,  0, 0, 2, 0, 0, 14, 0},
 {"boh", 0,  0, 0, 0, 0, 0, 14, 0},
 {0},
 {0}
};

Fl_Window* make_window() {
  Fl_Window* w;
  { Fl_Window* o = w = new Fl_Window(480, 500);
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 480, 25);
      o->menu(menu_);
    }
    o->end();
  }
  return w;
}
